Trim trailing slashes
messerli-informatik-ag/routing pull request #19
Opened 2019-10-09 15:00 UTC by bash

Resolves #17

2019-10-09 15:05 UTC, janhohenheim requested changes

2019-10-09 15:05 UTC, jnferner commented on Routing.Test/RoutingTest.cs
> +        public void CallsParentRouteWhenRequestPathEndsWithSegmentDelimiter()
Add test with multiple `/` at the end

2019-10-09 15:09 UTC, bash commented on Routing.Test/RoutingTest.cs
> +        public void CallsParentRouteWhenRequestPathEndsWithSegmentDelimiter()
Addressed in 7640a17

2019-10-09 15:10 UTC, janhohenheim approved these changes

2019-10-09 16:35 UTC, janhohenheim submitted a review, later dismissed

2019-10-10 08:02 UTC, janhohenheim submitted a review, later dismissed

2019-10-10 08:05 UTC, janhohenheim approved these changes

2019-10-10 08:09 UTC, merged